apiVersion: v1
kind: Namespace
metadata:
  creationTimestamp: "2020-08-05T17:53:54Z"
  name: git-metrix
---
apiVersion: v1
items:
- apiVersion: v1
  data:
    GIT_METRICS_CONFIG: |
      {"repositories":["kubeflow/kfctl","kubeflow/kfp-tekton","kubeflow/kfserving","kubeflow/kubeflow","kubeflow/manifests","kubeflow/mpi-operator","kubeflow/testing"],"githubToken":"e91ba8ebb8ebcd638346a0ad0a88296cc61f4967"}
  kind: ConfigMap
  metadata:
    name: git-metrix
    namespace: git-metrix
kind: List
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: git-metrix
  namespace: git-metrix
spec:
  replicas: 1
  selector:
    matchLabels:
      app: git-metrix
  template:
    metadata:
      labels:
        app: git-metrix
    spec:
      containers:
        - name: app
          image: 10.10.100.14:5000/git-metrics:1.1
          resources:
              requests:
                cpu: 1
                memory: 1000Mi
          ports:
            - containerPort: 5000
          envFrom:
          - configMapRef:
              name: git-metrix
          imagePullPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: git-metrix
  namespace: git-metrix
spec:
  selector:
    app: git-metrix
  ports:
    - port: 80
      targetPort: 5000
  type: LoadBalancer